### ISSUE TITLE
Installation method vs shipping a PKGBUILD

### ISSUE THREAD

**Issue by Zauberfisch** [EnigmaCurry/arch-ppa#13]
I agree with your statement that a AUR helper with `--no-confirm` is a scary thing.   
But that makes me even more surprised to see that `./arch-ppa setup` actually installs the `cower` from AUR without any user confirmation or review.

Is there a particular reason why this application is not packaged as an AUR page with cower (or some other helper) as a dependency?
That would make it more transparent to users what is being installed, and give users a chance to review installed AUR dependencies.

**Comment by EnigmaCurry** [comment]
Hi @Zauberfisch I'm not maintiaining this, because I don't use it any more. I'm very happy if you find this useful and you wish to fork it and/or improve it. I am going to archive this repo now, thanks for your understanding. I can link to your fork if you become an active maintainer, just get in touch: ryan@enigmacurry.com
